// <auto-generated />
using System;
using LogLens.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogLens.Infrastructure.Migrations
{
    [DbContext(typeof(LogLensDbContext))]
    [Migration("20260506172618_MultiTenancy_And_JSONB")]
    partial class MultiTenancy_And_JSONB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogLens.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ForecastId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ForecastId")
                        .HasDatabaseName("idx_alerts_forecastid");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("idx_alerts_incidentid");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_alerts_severity");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_alerts_timestamp");

                    b.HasIndex("Timestamp", "Severity")
                        .HasDatabaseName("idx_alerts_timestamp_severity");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawApiKeyCiphertext")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyPrefix")
                        .HasDatabaseName("idx_api_keys_prefix");

                    b.HasIndex("TenantId");

                    b.HasIndex("ServiceId", "IsActive")
                        .HasDatabaseName("idx_api_keys_service_active");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Forecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ForecastTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double>("PredictedValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ForecastTime")
                        .IsDescending()
                        .HasDatabaseName("idx_forecasts_forecasttime");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("idx_forecasts_incidentid");

                    b.HasIndex("PredictedValue")
                        .HasDatabaseName("idx_forecasts_predictedvalue");

                    b.ToTable("forecasts", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SuggestedCause")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_incidents_severity");

                    b.HasIndex("StartTimeUtc")
                        .IsDescending()
                        .HasDatabaseName("idx_incidents_starttime");

                    b.HasIndex("StartTimeUtc", "Severity")
                        .HasDatabaseName("idx_incidents_starttime_severity");

                    b.HasIndex("ServiceName", "StartTimeUtc", "Status")
                        .HasDatabaseName("idx_incidents_service_start_status");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClusterId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("idx_logs_clusterid");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("idx_logs_incidentid");

                    b.HasIndex("Level")
                        .HasDatabaseName("idx_logs_level");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("idx_logs_serviceid");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_logs_timestamp");

                    b.HasIndex("Timestamp", "Level")
                        .HasDatabaseName("idx_logs_timestamp_level");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_services_name");

                    b.HasIndex("TenantId");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("TenantId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Alert", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.Forecast", "Forecast")
                        .WithMany()
                        .HasForeignKey("ForecastId");

                    b.HasOne("LogLens.Domain.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId");

                    b.Navigation("Forecast");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.Service", "Service")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogLens.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Service");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Forecast", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.LogEntry", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.Incident", "Incident")
                        .WithMany("LogEntries")
                        .HasForeignKey("IncidentId");

                    b.HasOne("LogLens.Domain.Entities.Service", "Service")
                        .WithMany("Logs")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LogLens.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Incident");

                    b.Navigation("Service");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Service", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.User", "CreatedBy")
                        .WithMany("ServicesCreated")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogLens.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Services")
                        .HasForeignKey("TenantId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.User", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Incident", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Service", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.User", b =>
                {
                    b.Navigation("ServicesCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
