// <auto-generated />
using System;
using LogLens.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogLens.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LogLensDbContext))]
    [Migration("20260307154313_AddServiceNameAndTraceIdToLogs")]
    partial class AddServiceNameAndTraceIdToLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogLens.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ForecastId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ForecastId")
                        .HasDatabaseName("idx_alerts_forecastid");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("idx_alerts_incidentid");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_alerts_severity");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_alerts_timestamp");

                    b.HasIndex("Timestamp", "Severity")
                        .HasDatabaseName("idx_alerts_timestamp_severity");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Forecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ForecastTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double>("PredictedValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ForecastTime")
                        .IsDescending()
                        .HasDatabaseName("idx_forecasts_forecasttime");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("idx_forecasts_incidentid");

                    b.HasIndex("PredictedValue")
                        .HasDatabaseName("idx_forecasts_predictedvalue");

                    b.ToTable("forecasts", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_incidents_severity");

                    b.HasIndex("StartTime")
                        .IsDescending()
                        .HasDatabaseName("idx_incidents_starttime");

                    b.HasIndex("StartTime", "Severity")
                        .HasDatabaseName("idx_incidents_starttime_severity");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.LogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("Level")
                        .HasDatabaseName("idx_logs_level");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("idx_logs_timestamp");

                    b.HasIndex("Timestamp", "Level")
                        .HasDatabaseName("idx_logs_timestamp_level");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Alert", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.Forecast", "Forecast")
                        .WithMany()
                        .HasForeignKey("ForecastId");

                    b.HasOne("LogLens.Domain.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId");

                    b.Navigation("Forecast");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Forecast", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.LogEntry", b =>
                {
                    b.HasOne("LogLens.Domain.Entities.Incident", null)
                        .WithMany("LogEntries")
                        .HasForeignKey("IncidentId");
                });

            modelBuilder.Entity("LogLens.Domain.Entities.Incident", b =>
                {
                    b.Navigation("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
